name: Build status
on:
  push:
    paths:
      - '*.go'
      - 'pkg/*'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '*.go'
      - 'pkg/*'
      - '.github/workflows/build.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24.0
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: |
          make decloacker

