name: Publish release
on:
  push:
    tags:
      - "v*.*.*"
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: amd64
          - runner: ubuntu-24.04-arm
            target: arm64
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Set up Go 1.24.0
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        env:
          TAG: ${{ github.ref_name }}
        run: |
          sudo apt install libbpf-dev clang
          make
          echo "github release: ${{ github.sha }}" > checksums.txt
          sha256sum bin/decloaker > checksums.txt

          tar zcf "decloaker-$(date +%Y%m%d-$TAG)-${{ matrix.target }}.tar.gz" bin/decloaker README.md LICENSE checksums.txt
          cat checksums.txt
          ls -lh "decloaker-$(date +%Y%m%d-$TAG)-${{ matrix.target }}.tar.gz"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: yes
          generate_release_notes: yes
          files: |
            decloaker*.tar.gz

