name: Publish release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24.0
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        env:
          TAG: ${{ github.ref_name }}
        run: |
          make decloacker
          echo "github release: ${{ github.sha }}" > checksums.txt
          sha256sum bin/decloacker > checksums.txt

          tar zcf decloacker-$(date +%Y%m%d-$TAG).tar.gz bin/decloacker README.md LICENSE checksums.txt
          cat checksums.txt
          ls -lh decloacker-$(date +%Y%m%d-$TAG).tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: yes
          generate_release_notes: yes
          files: |
            declocker*.tar.gz

