name: Publish release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24.0
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: |
          make decloacker
          echo "github release: ${{ github.sha }}" > checksums.txt
          sha256sum bin/decloacker > checksums.txt

          tar zcf decloacker-$(date +%Y%m%d-v0.0.0).tar.gz bin/decloacker README.md LICENSE checksums.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          darft: yes
          files: |
            declocker*.tar.gz

